Repository Bastien-and-Gauvain/monorepo, pull requests merged in 2023-10, with the labels that each got.

#24 🎨 improvement(front) PLAS-047: Handle 'Go Back' in LinkedIn
  apps/linkedin-to-notion/src/background/index.ts
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/LinkedInNotionSidePanelContent.tsx
Labels: improvement, front

#26 🐛 fix(infra) : Mistakenly removed 'go back to LI' trigger
  apps/linkedin-to-notion/src/background/index.ts
Labels: fix, infra

#27 🎨 impr(infra) PLAS-049: Better regex that only matches when supposed to
  apps/linkedin-to-notion/src/background/index.ts
Labels: improvement, infra

#28 🐛 fix(front) PLAS-048: Scraping Complete Check Was Too Restrictive
  apps/linkedin-to-notion/src/contents/helpers.ts
Labels: fix, front

#31 🐛 fix(design,infra) PLAS-051: From Interfaces to Types to Avoid Build Errors
  libs/design-system/src/atoms/buttons/buttons.tsx
  libs/design-system/src/atoms/titles/titles.tsx
Labels: fix, infra, design

#30 ✨ feat(front,back) PLAS-42: Login and logout to Notion
  apps/linkedin-to-notion/src/background/index.ts
  apps/linkedin-to-notion/src/background/messages/sessions/resolvers/init-session.ts
  apps/linkedin-to-notion/src/background/messages/sessions/services/session.service.ts
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/LinkedInNotionSidePanelContent.tsx
  apps/linkedin-to-notion/src/contents/linkedin-notion-side-panel.tsx
  apps/linkedin-to-notion/src/options.tsx
  libs/design-system/src/molecules/IFramedSidePanel/IFramedSidePanel.stories.tsx
  libs/design-system/src/molecules/IFramedSidePanel/IFramedSidePanel.tsx
Labels: feature, front, back

#33 ✨ feat(back) PLAS-056: Store Notion API Tokens
  apps/linkedin-to-notion/package.json
  apps/linkedin-to-notion/src/background/index.ts
  apps/linkedin-to-notion/src/contents/linkedin-notion-side-panel.tsx
  pnpm-lock.yaml
Labels: feature, back

#34 ✨ feat(front) PLAS-055: Toggle Between LI and Notion values
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/Form.tsx
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/LinkedInNotionSidePanelContent.tsx
  libs/design-system/src/atoms/inputs/index.ts
  libs/design-system/src/atoms/inputs/inputs.stories.tsx
  libs/design-system/src/atoms/inputs/selectInputs.tsx
  libs/design-system/src/atoms/inputs/toggleInputs.tsx
  libs/design-system/src/molecules/formEntries/formEntries.stories.tsx
  libs/design-system/src/molecules/formEntries/index.ts
  libs/design-system/src/molecules/formEntries/selectEntry.tsx
  libs/design-system/src/molecules/formEntries/toggleEntry.tsx
Labels: feature, front

#42 ✨ feat (front,back) PLAS-054: Update Profile in Selected Database
  .vscode/settings.json
  apps/linkedin-to-notion/src/background/messages/notion/notion.transformers.ts
  apps/linkedin-to-notion/src/background/messages/notion/notion.type.ts
  apps/linkedin-to-notion/src/background/messages/notion/notionProfileInformationToNotionPage.ts
  apps/linkedin-to-notion/src/background/messages/notion/providers/notion.provider.ts
  apps/linkedin-to-notion/src/background/messages/notion/resolvers/findProfileInDatabase.ts
  apps/linkedin-to-notion/src/background/messages/notion/resolvers/updateProfileInDatabase.ts
  apps/linkedin-to-notion/src/background/shared.utils.ts
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/Alert.tsx
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/Form.tsx
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/LinkedInNotionSidePanelContent.tsx
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/NotionDatabasesSelect.tsx
Labels: feature, front, back
