Repository Bastien-and-Gauvain/monorepo, pull requests merged in 2023-11, with the labels that each got.

#48 ✨ feat(front,design) PLAS-063: Alerts Revamping
  libs/design-system/src/atoms/alerts/alerts.stories.tsx
  libs/design-system/src/atoms/icons/svg/ArrowRightTray.tsx
  libs/design-system/src/atoms/icons/svg/ChevronLeftRight.tsx
  libs/design-system/src/atoms/index.ts
  libs/design-system/src/molecules/alerts/alerts.stories.tsx
  libs/design-system/src/molecules/alerts/alerts.tsx
  libs/design-system/src/molecules/alerts/index.ts
  libs/design-system/src/molecules/index.ts
Labels: feature, design, front

#49 🎨 impr(front,design) PLAS-062: New Form Entries
  libs/design-system/package.json
  libs/design-system/src/atoms/icons/icons.stories.tsx
  libs/design-system/src/atoms/icons/svg/ArrowRightTray.tsx
  libs/design-system/src/atoms/icons/svg/ChevronDown.tsx
  libs/design-system/src/atoms/icons/svg/ChevronLeftRight.tsx
  libs/design-system/src/atoms/icons/svg/index.ts
  libs/design-system/src/atoms/inputs/inputs.stories.tsx
  libs/design-system/src/atoms/inputs/selectInputs.tsx
  libs/design-system/src/atoms/inputs/textAreaInputs.tsx
  libs/design-system/src/atoms/inputs/textInputs.tsx
  libs/design-system/src/atoms/inputs/toggleInputs.tsx
  libs/design-system/src/atoms/labels/labels.tsx
  libs/design-system/src/molecules/formEntries/formEntries.stories.tsx
  libs/design-system/src/molecules/formEntries/selectEntry.tsx
  libs/design-system/src/molecules/formEntries/toggleEntry.tsx
  libs/design-system/tailwind.config.js
  pnpm-lock.yaml
Labels: feature, design, front

#51 🎨 impr(front) PLAS-059: No 'Refresh' button on Notion values
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/Form.tsx
Labels: improvement, front

#52 ✨ feat(front, infra): PLAS-065: Bug Reporting Workflow
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/Alert.tsx
Labels: feature, infra

#53 ✨ feat(front,design) PLAS-69: All screens implemented
  apps/linkedin-to-notion/package.json
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/Alert.tsx
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/Form.tsx
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/FullScreenLoader.tsx
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/LinkedInNotionSidePanelContent.tsx
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/NotionDatabasesSelect.tsx
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/utils/formOptions.ts
  libs/design-system/src/atoms/inputs/selectInputs.tsx
  libs/design-system/src/molecules/alerts/alerts.tsx
  libs/design-system/src/molecules/index.ts
  libs/design-system/src/molecules/loader/index.ts
  libs/design-system/src/molecules/loader/loader.stories.tsx
  libs/design-system/src/molecules/loader/loader.tsx
  libs/design-system/tailwind.config.js
  monorepo.code-workspace
  pnpm-lock.yaml
Labels: feature, design, front

#56 🎨 impr(design) PLAS-081: Removed Unwanted Sscrollbar
  libs/design-system/src/molecules/IFramedSidePanel/IFramedSidePanel.tsx
Labels: improvement, design

#58 🎨 impr(design) PLAS-085: New Extension Icon
  apps/linkedin-to-notion/assets/icon.png
Labels: improvement, design

#55 🎨 impr(front,design) PLAS-076: Better Icons
  libs/design-system/src/atoms/buttons/buttons.stories.tsx
  libs/design-system/src/molecules/alerts/alerts.tsx
  libs/design-system/src/molecules/header/header.tsx
Labels: improvement, design, front

#62 🎨 impr(infra) PLAS-074: Burnt Useless Code and Files
  apps/linkedin-to-notion/src/background/index.ts
  apps/linkedin-to-notion/src/contents/scrapers/linkedin-profile-scraper.ts
  apps/linkedin-to-notion/src/options.tsx
  apps/linkedin-to-notion/src/tabs/welcome-page.tsx
  libs/design-system/src/atoms/icons/icons.stories.tsx
  libs/design-system/src/atoms/icons/svg/ArrowPath.tsx
  libs/design-system/src/atoms/icons/svg/ArrowRightTray.tsx
  libs/design-system/src/atoms/icons/svg/CheckCircle.tsx
  libs/design-system/src/atoms/icons/svg/ChevronDown.tsx
  libs/design-system/src/atoms/icons/svg/ChevronLeftRight.tsx
  libs/design-system/src/atoms/icons/svg/ExclamationCircle.tsx
  libs/design-system/src/atoms/icons/svg/InformationCircle.tsx
  libs/design-system/src/atoms/icons/svg/XMark.tsx
  libs/design-system/src/atoms/icons/svg/index.ts
  libs/design-system/src/molecules/header/header.tsx
Labels: improvement, infra

#63 🐛 fix(front) PLAS-087: Changed Company Selector
  apps/linkedin-to-notion/src/contents/scrapers/linkedin-profile-scraper.ts
Labels: fix, front

#65 🐛 fix(infra) PLAS-089: New Version and Headline
  apps/linkedin-to-notion/package.json
Labels: fix, infra

#68 🎨 impr(front,back) 54: form refacto
  apps/linkedin-to-notion/src/background/messages/notion/providers/notion.provider.ts
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/Form.tsx
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/Form/CallToAction.tsx
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/Form/Form.tsx
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/Form/formHelpers.ts
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/Form/formOptions.ts
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/LinkedInNotionSidePanelContent.tsx
  apps/linkedin-to-notion/src/components/LinkedInNotionSidePanel/NotionDatabasesSelect.tsx
Labels: improvement, infra
